### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by yin-qiyu** [hominsu/TensorRt-Yolov5-JetsonNano#1]
请问用的摄像头是csi的还是usb的

**Comment by hominsu** [comment]
usb摄像头
- 在我的jetson nano套件中，csi摄像头完全无法打开，按照官方文档的步骤来也不行，会直接宕机；
- 目前不知道是系统问题还是csi摄像头型号问题，总之目前来说使用usb摄像头是最优解。

**Comment by hominsu** [comment]
> 请问用的摄像头是csi的还是usb的

usb摄像头
- 在我的jetson nano套件中，csi摄像头完全无法打开，按照官方文档的步骤来也不行，会直接宕机；
- 目前不知道是系统问题还是csi摄像头型号问题，总之目前来说使用usb摄像头是最优解。

**Comment by yin-qiyu** [comment]
谢谢解答，我就是用csi摄像头 一调用摄像头机器就会重启 请问usb摄像头的话有规格要求呀

**Comment by hominsu** [comment]
> 谢谢解答，我就是用csi摄像头 一调用摄像头机器就会重启 请问usb摄像头的话有规格要求呀

目前来说，我使用的摄像头并没有遇到兼容问题。然后我也测试过两款分别是720p和1080p的罗技摄像头，以及一个不知名的4k摄像头都能正常使用。

**Comment by yin-qiyu** [comment]
好的谢谢
